Add Ubuntu instructions

diff --git a/manifests/vf-config.yaml b/manifests/vf-config.yaml
--- a/manifests/vf-config.yaml
+++ b/manifests/vf-config.yaml
@@ -51,13 +51,13 @@ spec:
                   sleep 15 ; continue ;
                 done
 
-                service stop oracle-cloud-agent || true
+                snap stop oracle-cloud-agent || true
                 echo 0 | tee /sys/class/net/rdma*/device/sriov_numvfs || true
                 sleep 30
                 rdma system show
                 oci-vf-config; sleep 2
                 echo 4220 | tee /sys/class/net/rdma*/mtu || true
-                service start oracle-cloud-agent || echo "Error restarting" >&2
+                snap start  oracle-cloud-agent || echo "Error restarting" >&2
                 crictl rmp -f "\$(crictl pods | grep sriov-device | awk '{print \$1}' | tail -1)" || true
               EOF
               while :; do { [[ $exit ]] && break; }; sleep 1; done # Sleep forever, exit gracefully
