Update docs for OL8

diff --git a/manifests/vf-config.yaml b/manifests/vf-config.yaml
--- a/manifests/vf-config.yaml
+++ b/manifests/vf-config.yaml
@@ -17,8 +17,18 @@ spec:
       hostNetwork: true
       tolerations: [{ operator: "Exists" }]
       terminationGracePeriodSeconds: 0
-      nodeSelector:
-        node.kubernetes.io/instance-type: BM.GPU.H100.8
+      affinity:
+        nodeAffinity:
+          requiredDuringSchedulingIgnoredDuringExecution:
+            nodeSelectorTerms:
+            - matchExpressions:
+              - key: node.kubernetes.io/instance-type
+                operator: In
+                values:
+                - BM.GPU.A100-v2.8
+                - BM.GPU.B4.8
+                - BM.GPU4.8
+                - BM.GPU.H100.8
       volumes: [{ name: root, hostPath: { path: "/" } }]
       containers:
         - name: vf-config
@@ -41,13 +51,13 @@ spec:
                   sleep 15 ; continue ;
                 done
 
-                snap stop oracle-cloud-agent || true
+                service stop oracle-cloud-agent || true
                 echo 0 | tee /sys/class/net/rdma*/device/sriov_numvfs || true
                 sleep 30
                 rdma system show
                 oci-vf-config; sleep 2
                 echo 4220 | tee /sys/class/net/rdma*/mtu || true
-                snap start  oracle-cloud-agent || echo "Error restarting" >&2
+                service start oracle-cloud-agent || echo "Error restarting" >&2
                 crictl rmp -f "\$(crictl pods | grep sriov-device | awk '{print \$1}' | tail -1)" || true
               EOF
               while :; do { [[ $exit ]] && break; }; sleep 1; done # Sleep forever, exit gracefully
